src/com/shf2/domain/User.java
package com.shf2.domain;

import java.text.SimpleDateFormat;
import java.util.Date;

public class User {
    private String name;
    private int age;
    private Date birthday;

//    逻辑方法
    public String getBitStr(){
        if (birthday!=null){
            SimpleDateFormat sdf = new SimpleDateFormat();
            return sdf.format(birthday);
        } else {
            return "";
        }

    }

    public User() {
    }

    public User(String name, int age, Date birthday) {
        this.name = name;
        this.age = age;
        this.birthday = birthday;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    @Override
    public String toString() {
        return "User{" +
                "name='" + name + '\'' +
                ", age=" + age +
                ", birthday=" + birthday +
                '}';
    }
}

web/jstl/jstl1.jsp
<%@ page import="java.util.ArrayList" %><%--
  Created by IntelliJ IDEA.
  User: SHF
  Date: 2021/9/13
  Time: 21:05
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>Title</title>
    <c:if test="false">我是真....</c:if>

    <%
        ArrayList arrayList = new ArrayList();
        arrayList.add("aaa");
        request.setAttribute("list",arrayList);

        request.setAttribute("number",3);
    %>

    <c:if test="${not empty list}">遍历集合...</c:if>
    
    <c:if test="${number%2==0}">
        ${number}为偶数
    </c:if>
    <c:if test="${number%2!=0}">
        ${number}为奇数
    </c:if>
</head>
<body>

</body>
</html>

web/jstl/jstl2.jsp
<%--
  Created by IntelliJ IDEA.
  User: SHF
  Date: 2021/9/13
  Time: 21:12
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
<%
    int number=5;
    request.setAttribute("num",number);
%>

<c:choose>
    <c:when test="${num==1}">星期一</c:when>
    <c:when test="${num==2}">星期二</c:when>
    <c:when test="${num==3}">星期三</c:when>
    <c:when test="${num==4}">星期四</c:when>
    <c:when test="${num==5}">星期五</c:when>
    <c:when test="${num==6}">星期六</c:when>
    <c:when test="${num==7}">星期七</c:when>
</c:choose>
</body>
</html>

web/jstl/jstl3.jsp
<%@ page import="java.util.ArrayList" %><%--
  Created by IntelliJ IDEA.
  User: SHF
  Date: 2021/9/13
  Time: 21:14
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
<c:forEach begin="1" end="10" var="i" step="2" varStatus="s">
    ${i}-------${s.index}-----${s.count} <br>
</c:forEach>

<hr>

<%
    ArrayList arrayList = new ArrayList();
    arrayList.add("aaa");
    arrayList.add("bbb");
    arrayList.add("ccc");
    request.setAttribute("list",arrayList);
%>

<c:forEach items="${list}" var="str" varStatus="s">
    ${s.index}-----${s.count}-------${str} <br>
</c:forEach>
</body>
</html>

web/jstl/jstlTest.jsp
<%@ page import="java.util.ArrayList" %>
<%@ page import="com.shf2.domain.User" %>
<%@ page import="java.util.Date" %><%--
  Created by IntelliJ IDEA.
  User: SHF
  Date: 2021/9/13
  Time: 21:25
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
<%
    ArrayList list = new ArrayList();
    list.add(new User("张三",23,new Date()));
    list.add(new User("李斯",24,new Date()));
    list.add(new User("王卫国",33,new Date()));
    request.setAttribute("list",list);
%>

<table border="1" align="center" width="500">
    <tr>
        <th>编号</th>
        <th>姓名</th>
        <th>年龄</th>
        <th>生日</th>
    </tr>
    <c:forEach var="user" items="${list}" varStatus="s">
        <c:if test="${s.count%2==0}">
            <tr bgcolor="aqua">
                <th>${s.count}</th>
                <th>${user.name}</th>
                <th>${user.age}</th>
                <th>${user.bitStr}</th>
            </tr>
        </c:if>
        <c:if test="${s.count%2!=0}">
            <tr bgcolor="#663399">
                <th>${s.count}</th>
                <th>${user.name}</th>
                <th>${user.age}</th>
                <th>${user.bitStr}</th>
            </tr>
        </c:if>

    </c:forEach>
</table>
</body>
</html>